### ISSUE TITLE
Money bug

### ISSUE THREAD

**Issue by stelstel** [stelstel/Flygprojekt#3]
Money.java:19: error: cannot find symbol

Money.java:29: error: cannot find symbol

**Comment by stelstel** [comment]
Better info:
C:\Users\User\Google Drive\Javakurs_stel\Projekt_stel\FlygProjekt01\src\flyace\Money.java:19: error: cannot find symbol
    private double price = ticket.getSeat().getPrice();
  symbol:   variable ticket
  location: class Money

**Comment by AmirDolkhani** [comment]
Hi Stefan , 
I'm on My way to work, i'll fix it Tonight and add My code, but if you need to fix now please change it as you wish. IF it's not urgent i'll fix it Tonight .

**Comment by stelstel** [comment]
Hi. Ok, no hurry.
//Stefan

AmirDolkhani notifications@github.com skrev: (13 juli 2016 17:06:17 CEST)

Hi Stefan ,
I'm on My way to work, i'll fix it Tonight and add My code, but if you need to fix now please change it as you wish. IF it's not urgent i'll fix it Tonight .

**Comment by AmirDolkhani** [comment]
Hi Stefan,
Do you still have problem with this bug or it got solved by last update?

**Comment by stelstel** [comment]
Its solved. Im closing this issue

**Comment by AmirDolkhani** [comment]
Thx Stefan.
