### ISSUE TITLE
Take off!

### ISSUE THREAD

**Issue by stelstel** [stelstel/Flygprojekt#5]
Now when you you add passengers by the addGroupOfPassengers() method until there are no empty seats the plane starts to refuel which is the first step of the flight! The next steps of the flight follows.

I made a new class called TimeToFly that is called from UI.

It didnt work calling it from PassengerPlane because the printing of the last "A ticket has been created successfully" would then appear after the flight! 

I put a line of code in UI at line 270 in the addGroupOfPassengers() method:
_TimeToFly.checkIfItsTime(ticket.getPlane());_ 

That line of code is probably needed to be copied to somewhere else too, please check that Kent!

**Comment by kentanderssonja** [comment]
När sista sätet är bokat, starta flygningen i en separat tråd och returnera ticketen (som vanligt).
När tråden är färdig, anropa någon metod som friställer säten och markerar planet klart för nya passagerar innan tråden dör.
