### ISSUE TITLE
Income calculation in class Money 

### ISSUE THREAD

**Issue by AmirDolkhani** [stelstel/Flygprojekt#6]
Any tips/ideas on how to get the price of the tickets and food items of all passengers?

**Comment by stelstel** [comment]
Price of the tickets u can get by looping through the seats when all seats are occupied. I tried this for the first two passangers, where pPlane is an PassangerPlane
_for(int i = 0; i < 10; i++){ 
  System.out.println("PRIS PASSAGERARE " + i + ":" + pPlane.getSeats().get(0).getPrice() );
}_
How to get the food price I dont know. Kent might know

**Comment by AmirDolkhani** [comment]
Thanks Steafn.

**Comment by kentanderssonja** [comment]
For FoodOrder there is a method getTotalCost() that returns cost as an interger, that you can use.
I can send foodOrders to yoy if you have a method, something like

public void methodName(FoodOrder foodOrder){
    int income = foodOrder.getTotalCost();

**Comment by AmirDolkhani** [comment]
Thanks Kent.

**Comment by kentanderssonja** [comment]
or it's possible to find it in the ticket, like this
ticket.getCustomer().getFoodorder().getTotalCost()
